/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ECodeRouteImport } from './routes/e.$code'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppSosRouteImport } from './routes/_authenticated/app.sos'
import { Route as AuthenticatedAppRemindersRouteImport } from './routes/_authenticated/app.reminders'
import { Route as AuthenticatedAppQrRouteImport } from './routes/_authenticated/app.qr'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppFamilyRouteImport } from './routes/_authenticated/app.family'
import { Route as AuthenticatedAppDocumentsRouteImport } from './routes/_authenticated/app.documents'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ECodeRoute = ECodeRouteImport.update({
  id: '/e/$code',
  path: '/e/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSosRoute = AuthenticatedAppSosRouteImport.update({
  id: '/app/sos',
  path: '/app/sos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRemindersRoute =
  AuthenticatedAppRemindersRouteImport.update({
    id: '/app/reminders',
    path: '/app/reminders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppQrRoute = AuthenticatedAppQrRouteImport.update({
  id: '/app/qr',
  path: '/app/qr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppFamilyRoute = AuthenticatedAppFamilyRouteImport.update({
  id: '/app/family',
  path: '/app/family',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppDocumentsRoute =
  AuthenticatedAppDocumentsRouteImport.update({
    id: '/app/documents',
    path: '/app/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/e/$code': typeof ECodeRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/family': typeof AuthenticatedAppFamilyRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/qr': typeof AuthenticatedAppQrRoute
  '/app/reminders': typeof AuthenticatedAppRemindersRoute
  '/app/sos': typeof AuthenticatedAppSosRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/e/$code': typeof ECodeRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/family': typeof AuthenticatedAppFamilyRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/qr': typeof AuthenticatedAppQrRoute
  '/app/reminders': typeof AuthenticatedAppRemindersRoute
  '/app/sos': typeof AuthenticatedAppSosRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/e/$code': typeof ECodeRoute
  '/_authenticated/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/_authenticated/app/family': typeof AuthenticatedAppFamilyRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/qr': typeof AuthenticatedAppQrRoute
  '/_authenticated/app/reminders': typeof AuthenticatedAppRemindersRoute
  '/_authenticated/app/sos': typeof AuthenticatedAppSosRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/e/$code'
    | '/app/documents'
    | '/app/family'
    | '/app/profile'
    | '/app/qr'
    | '/app/reminders'
    | '/app/sos'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/e/$code'
    | '/app/documents'
    | '/app/family'
    | '/app/profile'
    | '/app/qr'
    | '/app/reminders'
    | '/app/sos'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/e/$code'
    | '/_authenticated/app/documents'
    | '/_authenticated/app/family'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/qr'
    | '/_authenticated/app/reminders'
    | '/_authenticated/app/sos'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ECodeRoute: typeof ECodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$code': {
      id: '/e/$code'
      path: '/e/$code'
      fullPath: '/e/$code'
      preLoaderRoute: typeof ECodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sos': {
      id: '/_authenticated/app/sos'
      path: '/app/sos'
      fullPath: '/app/sos'
      preLoaderRoute: typeof AuthenticatedAppSosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/reminders': {
      id: '/_authenticated/app/reminders'
      path: '/app/reminders'
      fullPath: '/app/reminders'
      preLoaderRoute: typeof AuthenticatedAppRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/qr': {
      id: '/_authenticated/app/qr'
      path: '/app/qr'
      fullPath: '/app/qr'
      preLoaderRoute: typeof AuthenticatedAppQrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/family': {
      id: '/_authenticated/app/family'
      path: '/app/family'
      fullPath: '/app/family'
      preLoaderRoute: typeof AuthenticatedAppFamilyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/documents': {
      id: '/_authenticated/app/documents'
      path: '/app/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AuthenticatedAppDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppDocumentsRoute: typeof AuthenticatedAppDocumentsRoute
  AuthenticatedAppFamilyRoute: typeof AuthenticatedAppFamilyRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppQrRoute: typeof AuthenticatedAppQrRoute
  AuthenticatedAppRemindersRoute: typeof AuthenticatedAppRemindersRoute
  AuthenticatedAppSosRoute: typeof AuthenticatedAppSosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppDocumentsRoute: AuthenticatedAppDocumentsRoute,
  AuthenticatedAppFamilyRoute: AuthenticatedAppFamilyRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppQrRoute: AuthenticatedAppQrRoute,
  AuthenticatedAppRemindersRoute: AuthenticatedAppRemindersRoute,
  AuthenticatedAppSosRoute: AuthenticatedAppSosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ECodeRoute: ECodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
